name: vude_story_editor
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.0
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  video_thumbnail: ^0.5.3
  flutter_linkify: ^6.0.0
  linkify: ^5.0.0
  text_scroll: ^0.2.0
  just_audio: ^0.9.36
  animated_text_kit: ^4.2.2
  dio: ^5.4.1
  emoji_picker_flutter: ^1.6.2
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.2
  collection: ^1.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: aveny-t
      fonts:
        - asset: fonts/Aveny-T.ttf
    - family: cosmopolitan
      fonts:
        - asset: fonts/Cosmopolitan-Script-Regular.otf
    - family: courier
      fonts:
        - asset: fonts/Courier-Bold.ttf
    - family: comic
      fonts:
        - asset: fonts/Comic-Sans-MS3.ttf
    - family: Gilmer
      fonts:
        - asset: fonts/Gilmer-Regular.otf
    - family: roboto
      fonts:
        - asset: fonts/Roboto-Italic.ttf
    - family: sans-fransisco
      fonts:
        - asset: fonts/Sans-Fransisco-Bold.ttf
    - family: winslow-book
      fonts:
        - asset: fonts/winslow-book-regular-italic.otf
    - family: brutal-type
      fonts:
        - asset: fonts/Brutal-Type-Medium.ttf
    - family: noto-emoji
      fonts:
        - asset: fonts/NotoColorEmoji-Regular.ttf
    
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
